env:
  CIRRUS_CLONE_DEPTH: "1"
  BUILD_HOSTNAME: "cirrus-ci.org"
  RCLONECONFIG_DRIVE: ENCRYPTED[!44519898876228cb2f5b2de25015c13fa553d370120353198e1333180141c958de154757fd29a76699f07e44722b88f9!]
  TG_TOKEN: ENCRYPTED[!0961b960b9a583cdfb79ea69872cc2c0d19f432982e81e66d597ae8754e56ca291d77c7504126ce9b340b73d5264b6ce!]
  TG_CHAT_ID: ENCRYPTED[!dfa7f4b024b6fe39df76ed8d6276e9e3d2bdc21de92ae1bf2308906cf6560557b869d3148f58487e231c72a5e64358f0!]
  WORKDIR: "/tmp"
  EMAIL: ENCRYPTED[e0ca201ca6feddee4033e308f1d6b5a3480e78604e1bc3112aa91c545a649cd129b7728b1745133d980c630ef9897152]
  credentials: ENCRYPTED[cc4d78790578ad8c891a3bfc2eb98e9a9076d1a7cec7ead728ad945625b9e8cddd91076d7af667bd4024ce6995ba6dcb]

task:
  name: "Build roms"
  only_if: $CIRRUS_REPO_OWNER == 'HAPPEX7'
  timeout_in: 150m
  container:
    image: anggit86/ubuntu:22.04
    cpu: 8
    memory: 32G

  Load-Ccache_background_script:
     - ./script/load_ccache.sh

  Sync-rom_script:
     - git config --global user.name "Happex7"
     - git config --global user.email "$EMAIL"
     - echo "$credentials" > ~/.git-credentials
     - git config --global credential.helper store --file=~/.git-credentials
     - ./script/sync.sh
     
  Build-rom_script:
     - ./script/building.sh
     
  Ccache-info_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Upload-build_script:
     - ./script/ziping.sh
